### ISSUE TITLE
Object namespaces don't seem to lookup i18n keys appropriately

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/formulaic#19]
The following name-spaced class:

```
class Admin::Reservation
  # some stuff
end
```

requires i18n keys such as:

```
activemodel:
  attributes:
    admin/reservation:
      field: 'Name'
```

But it seems like formulaic is dropping the namespace.
