### ISSUE TITLE
Rails SimpleForm I18n Formulaic::InputNotFound

### ISSUE THREAD

**Issue by LiliyaSabitova** [thoughtbot/formulaic#31]
Example:

We have simple form for user with email field

``` ruby
f.input :email
```

and we have simple_form.en.yml

``` yaml
labels:
      user:
        new:
          email: 'Enter your email address'
```

when we try to fill in form like here

``` ruby
fill_form(
  :user,
  email: email,
  password: password
)
```

then we get error

``` sh
Formulaic::InputNotFound:
       Unable to find input "Email".
```

so we have to do like here

``` ruby
fill_form(
  :user,
  'Enter your email address' => email,
  password: password
)
```
